language: cpp
compiler: g++
dist: xenial

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test-cover/ | xargs clang-format -i && git diff --exit-code
  - make
  - make test
